



// ************************ ПРАКТИЧЕСКАЯ ЧАСТЬ. *************/
// СОЗДАЕМ ПРИЛОЖЕНИЕ

/* 17 Урок
   

   App.js

   Navbar.jsx
   Profile.jsx
        MyPosts.jsx
           Post.jsx
   Dialogs.jsx
        DialogItem.jsx
        Message.jsx

   17. Теперь мы разместим данные в index.js и будем через props их передавать во все наши другие компоненты.
       Это начальное представление React и Redux.
       
   */