



// ************************ ПРАКТИЧЕСКАЯ ЧАСТЬ. *************/
// СОЗДАЕМ ПРИЛОЖЕНИЕ

/* 22 Урок
   
   state.js

   index.js
   App.jsx
   Profile.jsx
   MyPosts.jsx
     
     В файле state.js создали функцию addPost, которая в базу данных state вносит новый объект с данными.
     
     Потом через props функцию addPost предали в index.js - App.jsx - Profile.jsx и в MyPosts.jsx. 
     В MyPosts.jsx при нажатии на кнопку запускаеться функция addPostClick, 
     которая запускает нашу функцию addPost с добавлениями данных из textarea в базу данных state в файле state.jsx.

     Вот так.

   */