



// ************************ ПРАКТИЧЕСКАЯ ЧАСТЬ. *************/
// СОЗДАЕМ ПРИЛОЖЕНИЕ

/* 19 Урок
   
   state.js - данные Redux
   index.js - import let state = {}

   App.js - отрисовка React
      Profile.jsx
          MyPosts.jsx
                Post.jsx
          Dialogs.jsx
                DialogItem.jsx
                Message.jsx

   19. Теперь мы разместим данные в state.js 
       и передали данные через props в index.js 
       и потом предали данные во все наши другие компоненты, которые нарисовали все по данным.

       Вот.
   */